#!/bin/sh

if [ -z "$1" ]; then
LAST_N=1
else
LAST_N=$1
fi
if which mvim > /dev/null 2>&1; then
VIM=mvim
else
VIM=vim
fi
$VIM $(grep 'created_at' content/posts/*.markdown | awk -F: '{ print $3, "---", $1 }' | sort | awk -F--- '{ print $2 }' | tail -n${LAST_N} | head -n1)

