#!/bin/sh

USER="ec2-user"
HOST="pentandra.com"
SSH_KEY="$HOME/.ssh/pentandraec2key.pem"

rsync \
  -vz \
  -e "ssh -i $SSH_KEY" \
  --rsync-path="sudo rsync" \
  {nginx.conf,mime.types} $USER@$HOST:/etc/nginx/

ssh -i $SSH_KEY $USER@$HOST 'sudo service nginx reload'
