# -*- encoding: utf-8 -*-
# frozen_string_literal: true
# This file generated automatically using rdf vocabulary format from http://purl.org/essglobal/vocab/
require 'rdf'
module Vocab
  # @!parse
  #   # Vocabulary for <http://purl.org/essglobal/vocab/>
  #   class ESSGLOBAL < RDF::StrictVocabulary
  #   end
  class ESSGLOBAL < RDF::StrictVocabulary("http://purl.org/essglobal/vocab/")

    # Property definitions
    property :"1.0/isMain",
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:LocationOfSale".freeze,
      label: "Is Main".freeze,
      range: "rdfs:boolean".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :availableAt,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:SaleOption".freeze,
      label: "Available At".freeze,
      :"owl:equivalentProperty" => [],
      range: "essglobal:LocationOfSale".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :costPerUnit,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:Input".freeze,
      label: "Cost per Unit".freeze,
      range: "rdfs:decimal".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :deliveryRangeDistance,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:LocationOfSale".freeze,
      label: "Delivery Range (distance)".freeze,
      range: "rdfs:decimal".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :economicSector,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:SSEInitiative".freeze,
      label: "Economic Sector".freeze,
      :"rdfs:Datatype" => [],
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :hasAddress,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: ["essglobal:Network".freeze, "essglobal:ProductOrService".freeze],
      label: "Has an Address".freeze,
      range: "essglobal:LocationOfSale".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :hasCost,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:ProductOrService".freeze,
      label: "Has Cost".freeze,
      range: "essglobal:Cost".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :hasImpactOnPrice,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: ["essglobal:Input".freeze, "essglobal:OtherCosts".freeze],
      label: "Has impact on price".freeze,
      range: "rdfs:boolean".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :hasInputCost,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:CostComposition".freeze,
      label: "Has input".freeze,
      range: "essglobal:Input".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :hasLabourCost,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:CostComposition".freeze,
      label: "Has Labour".freeze,
      range: "essglobal:Labour".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :hasOtherCosts,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:CostComposition".freeze,
      label: "Has Other Costs".freeze,
      range: "essglobal:OtherCosts".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :hasProductOrService,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: ["essglobal:Network".freeze, "essglobal:SSEInitiative".freeze],
      label: "Has Product or Service".freeze,
      :"owl:equivalentProperty" => [],
      range: "essglobal:ProductOrService".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :hasSaleOption,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:ProductOrService".freeze,
      label: "Has a Sale Option".freeze,
      range: "essglobal:SaleOption".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :isAvailable,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:SaleOption".freeze,
      label: "Is available".freeze,
      range: "rdfs:boolean".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :isComposedBy,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:Cost".freeze,
      label: "Is Composed By".freeze,
      range: "essglobal:CostComposition".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :isSSE,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:LocationOfSale".freeze,
      label: "Is SSE Initiative".freeze,
      range: "rdfs:boolean".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :legalForm,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: ["essglobal:Network".freeze, "essglobal:SSEInitiative".freeze],
      label: "Legal Form".freeze,
      :"rdfs:Datatype" => [],
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :mission,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: ["essglobal:Network".freeze, "essglobal:SSEInitiative".freeze],
      label: "Mission".freeze,
      range: "rdfs:Literal".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :objective,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: ["essglobal:Network".freeze, "essglobal:SSEInitiative".freeze],
      label: "Objective".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :qualifier,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: ["essglobal:Input".freeze, "essglobal:ProductOrService".freeze],
      label: "Qualifier".freeze,
      :"rdfs:Datatype" => [],
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :quantityPerProductOrServiceUnit,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:Input".freeze,
      label: "Quantity per Product or Service Unit".freeze,
      range: "rdfs:decimal".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :salesMarginPercentage,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:SaleOption".freeze,
      label: "Sales Margin (percentage)".freeze,
      range: "rdfs:decimal".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :salesMarginValue,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:SaleOption".freeze,
      label: "Sales Margin (value)".freeze,
      range: "rdfs:decimal".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :state,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:Address".freeze,
      label: "State".freeze,
      range: "rdfs:Literal".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :totalMen,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:SSEInitiative".freeze,
      label: "Total of Men".freeze,
      range: "http://http://www.w3.org/2001/XMLSchema#nonNegativeInteger".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :totalOfMembers,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:SSEInitiative".freeze,
      label: "Total of Members".freeze,
      range: "http://http://www.w3.org/2001/XMLSchema#nonNegativeInteger".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :totalWomen,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:SSEInitiative".freeze,
      label: "Total of Women".freeze,
      range: "http://http://www.w3.org/2001/XMLSchema#nonNegativeInteger".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :typeOfLabour,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:Labour".freeze,
      label: "Type of Labour".freeze,
      :"rdfs:Datatype" => [],
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze
    property :unit,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      domain: "essglobal:Input".freeze,
      label: "Unit".freeze,
      range: "rdfs:Literal".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Property".freeze

    # Extra definitions
    term :Address,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      label: "Address".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Class".freeze
    term :Cost,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      label: "Cost".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Class".freeze
    term :CostComposition,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      label: "Cost Composition".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Class".freeze
    term :Input,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      label: "Input".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Class".freeze
    term :Labour,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      label: "Labour".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Class".freeze
    term :LocationOfSale,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      label: "Location of Sale".freeze,
      :"rdfs:isDefinedBy" => [],
      subClassOf: "http://purl.org/goodrelations/v1/Location".freeze,
      type: "rdf:Class".freeze
    term :Network,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      label: "Network".freeze,
      :"rdfs:isDefinedBy" => [],
      subClassOf: "http://www.w3.org/ns/org/OrganizationColaboration".freeze,
      type: "rdf:Class".freeze
    term :OtherCosts,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      label: "Other Costs".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Class".freeze
    term :ProductOrService,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      label: "Product or Service".freeze,
      :"rdfs:isDefinedBy" => [],
      subClassOf: "http://purl.org/goodrelations/v1/ProductOrService".freeze,
      type: "rdf:Class".freeze
    term :SSEInitiative,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      label: "SSE Initiative".freeze,
      :"rdfs:isDefinedBy" => [],
      subClassOf: "http://www.w3.org/ns/org/OrganizationUnit".freeze,
      type: "rdf:Class".freeze
    term :SaleOption,
      :"dc:description" => [],
      :"dc:issued" => [],
      :"dc:modified" => [],
      label: "Sale Option".freeze,
      :"rdfs:isDefinedBy" => [],
      type: "rdf:Class".freeze
  end
end
