#!/bin/sh

SCRIPT_PATH=$(dirname `which $0`)

YEAR=$(date +%Y)
MONTH=$(date +%m)
DAY=$(date +%d)
/bin/echo -n "Enter title: "
read RAW_TITLE
/bin/echo -n "Enter description: "
read DESCRIPTION
/bin/echo -n "Enter your name: "
read AUTHOR

TITLE=$(echo "$RAW_TITLE" | sed -e 's/[ _]/-/g' -e 's/[^a-zA-Z0-9-]//g' -e 's/-$//g' -e 's/\(.*\)/\L\1/')

mkdir $SCRIPT_PATH/../items/static/blog/$TITLE

echo "---
title: $RAW_TITLE
description: $DESCRIPTION
kind: article
author_name: $AUTHOR
created_at: $YEAR-$MONTH-$DAY
updated_at: $YEAR-$MONTH-$DAY
published: false
tags: []
---
This is your new post." > "$SCRIPT_PATH/../items/static/blog/$TITLE/index.md"

echo "Created items/static/blog/$TITLE/index.md"
