# -*- encoding: utf-8 -*-
# frozen_string_literal: true
# This file generated automatically using rdf vocabulary format from http://dbpedia.org/resource/
require 'rdf'
module RDF::Vocab
  # @!parse
  #   # Vocabulary for <http://dbpedia.org/resource/>
  #   class DBR < RDF::Vocabulary
  #   end
  class DBR < RDF::Vocabulary("http://dbpedia.org/resource/")

    # Ontology definition
    ontology :"http://dbpedia.org/resource/",
      comment: %( \(pronounced "five hundred px"\) is a Canadian online community and marketplace based on photography, co-founded by Oleg Gutsol and Evgeny Tchebotarev \(artistically also known as “Ian Sobolev”\) on Halloween 2009. The Toronto-based startup launched its Web 2.0 version in 2009 and is aimed at aspiring and professional photographers; encouraging members to upload their best work. In August 2015, the company launched a new version of its iOS app.).freeze,
      "http://dbpedia.org/ontology/abstract": " (pronounced \"five hundred px\") is a Canadian online community and marketplace based on photography, co-founded by Oleg Gutsol and Evgeny Tchebotarev (artistically also known as “Ian Sobolev”) on Halloween 2009. The Toronto-based startup launched its Web 2.0 version in 2009 and is aimed at aspiring and professional photographers; encouraging members to upload their best work. In August 2015, the company launched a new version of its iOS app.  is seen as a place to gain exposure, find inspiration and connect photographers with one another. As of January 2016, the site had 7 million users.".freeze,
      "owl:sameAs": "dbr:".freeze

    # Extra definitions
    term :"2012–13_EHF_Champions_League_knockout_stage",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"2012–13_LEN_Champions_League_knockout_stage",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Andrei_Alexandrescu,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"Asunder_(software)",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :BMW_503,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Bay_Area_Ridge_Trail,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"Bay_Road_(Bristol_County,_Massachusetts)",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Biquaternion,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Bruckner_rhythm,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Buick_Blackhawk,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Covenant_Fellowship_Church,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :DHR_D_Class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Diazenylium,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Doubly_ionized_oxygen,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :EAR_56_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :EAR_58_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :EAR_60_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Egypt_Standard_Time,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"FS-A1WSX",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"Ferrari_365_GT4_2_2,_400_and_412",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"Ferrari_365_GTC/4",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Ferrari_612_Scaglietti,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Fiat_124_Sport_Spider,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :GParted,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"Greg_Hastings_Tournament_Paintball_MAX'D",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :HiC,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :ISABELLE,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :International_cricket_in_2006–07,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"J-Pilot",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :KUR_EC1_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :KUR_EC2_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :KUR_EC3_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :KUR_EC4_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :KUR_EC5_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :KUR_EC_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"Kino_(software)",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :La_Chonita_Hacienda,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Lamborghini_Jarama,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :List_of_Alberta_area_codes,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Maserati_3200_GT,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Maserati_Alfieri,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :NGC_5886,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :New_South_Wales_AD60_class_locomotive,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Northeast_Texas_Trail,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Open_Inventor,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :OverSim,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Pantheios,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Passpo,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Politics_of_Indiana,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Porsche_911,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Proteus_vulgaris,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Qt_Creator,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Rude_and_Smooth,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"Sisu_K-44",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Sound_Juicer,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"Synaptic_(software)",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :TR_GA_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Telephone_numbers_in_Bangladesh,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Telephone_numbers_in_Iceland,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Telephone_numbers_in_Kosovo,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Telephone_numbers_in_Uruguay,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Time_in_Kazakhstan,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Transitive_closure,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :Voices_in_Harmony,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :WAGR_M_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :WAGR_Msa_class,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :"X-CD-Roast",
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
    term :YkoK_leader,
      "http://purl.org/linguistics/gold/hypernym": "dbr:".freeze
  end
end
