# -*- encoding: utf-8 -*-
# frozen_string_literal: true
# This file generated automatically using rdf vocabulary format from http://purl.org/essglobal/vocab/
require 'rdf'
module RDF::Vocab
  # @!parse
  #   # Vocabulary for <http://purl.org/essglobal/vocab/>
  #   class ESSGLOBAL < RDF::StrictVocabulary
  #   end
  class ESSGLOBAL < RDF::StrictVocabulary("http://purl.org/essglobal/vocab/")

    # Property definitions
    property :"1.0/isMain",
      :"dc:description" => %(If the Location of Sale is the headquarter of the SSE initiative?).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:LocationOfSale".freeze,
      label: "Is Main".freeze,
      range: "rdfs:boolean".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/1.0/).freeze,
      type: "rdf:Property".freeze
    property :availableAt,
      :"dc:description" => %(A Product or Service is sold at a sale location under specific definitions.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:SaleOption".freeze,
      label: "Available At".freeze,
      :"owl:equivalentProperty" => %(http://purl.org/goodrelations/v1/availableAtOrFrom).freeze,
      range: "essglobal:LocationOfSale".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :costPerUnit,
      :"dc:description" => %(The cost per unit of input.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:Input".freeze,
      label: "Cost per Unit".freeze,
      range: "rdfs:decimal".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :deliveryRangeDistance,
      :"dc:description" => %(Delivery range of product or service, in kilometers or miles.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:LocationOfSale".freeze,
      label: "Delivery Range (distance)".freeze,
      range: "rdfs:decimal".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :economicSector,
      :"dc:description" => %(A categorization of the type of activities carried on by SSE initiatives, depending of its nature, raw materials and methodology.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:SSEInitiative".freeze,
      label: "Economic Sector".freeze,
      :"rdfs:Datatype" => %(http://purl.org/essglobal/standard/activities/).freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :hasAddress,
      :"dc:description" => %(The address that the SSE initiative, Network or Location of Sale have.).freeze,
      :"dc:issued" => %(2015-05-04).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: ["essglobal:Network".freeze, "essglobal:ProductOrService".freeze],
      label: "Has an Address".freeze,
      range: "essglobal:LocationOfSale".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :hasCost,
      :"dc:description" => %(The cost for a particular product or service produced by an SSE initiative or network.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:ProductOrService".freeze,
      label: "Has Cost".freeze,
      range: "essglobal:Cost".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :hasImpactOnPrice,
      :"dc:description" => %(Does the input contribute to the monetary price of the final product? Whereas many \(perhaps most\) inputs do contribute to the monetary price of the final product or service, some don't. For example, volunteer labour may contribute greatly to production without adding to the monetary cost of production. 
).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: ["essglobal:Input".freeze, "essglobal:OtherCosts".freeze],
      label: "Has impact on price".freeze,
      range: "rdfs:boolean".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :hasInputCost,
      :"dc:description" => %(A product, service, or activity that goes into making the final product or service.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:CostComposition".freeze,
      label: "Has input".freeze,
      range: "essglobal:Input".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :hasLabourCost,
      :"dc:description" => %(Work done for specific tasks related to the provision of goods or services offered by the SSE initiative. Generally it can be human, animal or machine labour, but in ESSglobal it's human labour only.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:CostComposition".freeze,
      label: "Has Labour".freeze,
      range: "essglobal:Labour".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :hasOtherCosts,
      :"dc:description" => %(Other costs which impact on the final cost of a product or service provided by an SSE initiative, other than input or labour, like taxes, deprecation of machinery, funds, etc. The delivery costs are not included in these costs: they are included in the sale-options class.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:CostComposition".freeze,
      label: "Has Other Costs".freeze,
      range: "essglobal:OtherCosts".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :hasProductOrService,
      :"dc:description" => %(A Network or SSE Initiative produce products or make available services.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: ["essglobal:Network".freeze, "essglobal:SSEInitiative".freeze],
      label: "Has Product or Service".freeze,
      :"owl:equivalentProperty" => %(http://purl.org/goodrelations/v1/offers).freeze,
      range: "essglobal:ProductOrService".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :hasSaleOption,
      :"dc:description" => %(A sale option si connected to a place where the good or service is provided.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:ProductOrService".freeze,
      label: "Has a Sale Option".freeze,
      range: "essglobal:SaleOption".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :isAvailable,
      :"dc:description" => %(If the Sale Option \(the product/service at a certain price, under specific properties, in a specific Sale Location\) is available.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:SaleOption".freeze,
      label: "Is available".freeze,
      range: "rdfs:boolean".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :isComposedBy,
      :"dc:description" => %(A breakdown of all inputs \(as taxes and raw materials\) and labour costs that make up the product or service's final cost. An open cost is a pre-requisite for solidarity fair trade systems.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:Cost".freeze,
      label: "Is Composed By".freeze,
      range: "essglobal:CostComposition".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :isSSE,
      :"dc:description" => %(If the Location of Sale is a place belonging to the SSE.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:LocationOfSale".freeze,
      label: "Is SSE Initiative".freeze,
      range: "rdfs:boolean".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :legalForm,
      :"dc:description" => %(The legal form of a SSE Initiative or Network.To be described.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: ["essglobal:Network".freeze, "essglobal:SSEInitiative".freeze],
      label: "Legal Form".freeze,
      :"rdfs:Datatype" => %(http://purl.org/essglobal/standard/legal-form/).freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :mission,
      :"dc:description" => %(The initiative's vision, values, and principles.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: ["essglobal:Network".freeze, "essglobal:SSEInitiative".freeze],
      label: "Mission".freeze,
      range: "rdfs:Literal".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :objective,
      :"dc:description" => %(Actionable and measurable steps the SSE Initiative is taking to carry out its mission. ).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: ["essglobal:Network".freeze, "essglobal:SSEInitiative".freeze],
      label: "Objective".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :qualifier,
      :"dc:description" => %(
		Aspect that differentiates the product or service of an SSE initiative which is related to the form of production, the actors involved, the use of only organic materials, etc. 
		Examples are organic, permacultural, made with recycled raw materials, indigenous, made by women, etc.
   ).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: ["essglobal:Input".freeze, "essglobal:ProductOrService".freeze],
      label: "Qualifier".freeze,
      :"rdfs:Datatype" => %(http://purl.org/essglobal/standard/qualifiers/).freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :quantityPerProductOrServiceUnit,
      :"dc:description" => %(The quantity of the input that goes into providing one unit of the final product or service. ).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:Input".freeze,
      label: "Quantity per Product or Service Unit".freeze,
      range: "rdfs:decimal".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :salesMarginPercentage,
      :"dc:description" => %(
		Margin \(on sales\) is the difference between selling price and cost. This difference is typically expressed either as a percentage of selling price or on a per-unit basis. This attribute is the percentage sales margin. 
   ).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:SaleOption".freeze,
      label: "Sales Margin (percentage)".freeze,
      range: "rdfs:decimal".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :salesMarginValue,
      :"dc:description" => %(
		Margin \(on sales\) is the difference between selling price and cost. This difference is typically expressed either as a percentage of selling price or on a per-unit basis. The present attribute is an absolute value for sales margin on each unit of the product or service offered in the location.
	).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2014-04-15).freeze,
      domain: "essglobal:SaleOption".freeze,
      label: "Sales Margin (value)".freeze,
      range: "rdfs:decimal".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :state,
      :"dc:description" => %(The State of the Address.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:Address".freeze,
      label: "State".freeze,
      range: "rdfs:Literal".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :totalMen,
      :"dc:description" => %(The number of men that work in the SSE Initiative.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:SSEInitiative".freeze,
      label: "Total of Men".freeze,
      range: "http://http://www.w3.org/2001/XMLSchema#nonNegativeInteger".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :totalOfMembers,
      :"dc:description" => %(The total number of members that work in the SSE Initiative.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:SSEInitiative".freeze,
      label: "Total of Members".freeze,
      range: "http://http://www.w3.org/2001/XMLSchema#nonNegativeInteger".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :totalWomen,
      :"dc:description" => %(The number of women that work in the SSE Initiative.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:SSEInitiative".freeze,
      label: "Total of Women".freeze,
      range: "http://http://www.w3.org/2001/XMLSchema#nonNegativeInteger".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :typeOfLabour,
      :"dc:description" => %(The human labour dedicated for providing goods or services can be of different types, depending on the established labour relations. For example, it might be associative \(i.e., the worker is one of the collective owners of the SSE initiative\), but it might also be subordinated work \(an employee of the SSE initiative\), volunteer work or externally hired work \(like a freelancer or a partner initiative\).).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:Labour".freeze,
      label: "Type of Labour".freeze,
      :"rdfs:Datatype" => %(http://purl.org/essglobal/standard/type-of-labour/).freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze
    property :unit,
      :"dc:description" => %(The unit that a product or service is measured in, in the Universal Unit System \(e.g., kilograms, hours\)).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      domain: "essglobal:Input".freeze,
      label: "Unit".freeze,
      range: "rdfs:Literal".freeze,
      :"rdfs:isDefinedBy" => %(essglobal:).freeze,
      type: "rdf:Property".freeze

    # Extra definitions
    term :Address,
      :"dc:description" => %(A phisical address of a Location of sale, of a SSE Initiative or of a Network ).freeze,
      :"dc:issued" => %(2015-05-04).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      label: "Address".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/).freeze,
      type: "rdf:Class".freeze
    term :Cost,
      :"dc:description" => %(The cost for a particular product or service produced by an SSE initiative or network, including all costs. The price will be this cost added to delivery costs and sales margin as can be seen in the sale-option class.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      label: "Cost".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/).freeze,
      type: "rdf:Class".freeze
    term :CostComposition,
      :"dc:description" => %(A breakdown of all inputs \(as taxes and raw materials\) and labour costs that make up the product or service's final cost. An open cost is a pre-requisite for solidarity fair trade systems. ).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      label: "Cost Composition".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/).freeze,
      type: "rdf:Class".freeze
    term :Input,
      :"dc:description" => %(A product, service, or activity that goes into making the final product or service. ).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      label: "Input".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/).freeze,
      type: "rdf:Class".freeze
    term :Labour,
      :"dc:description" => %(Work done for specific tasks related to the provision of goods or services offered by the SSE initiative. Generally it can be human, animal or machine labour, but in ESSglobal it's human labour only.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      label: "Labour".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/).freeze,
      type: "rdf:Class".freeze
    term :LocationOfSale,
      :"dc:description" => %(Place where the goods or services of an SSE initiative are provided. It can be self owned shops, but also partner places where the products or services are available among those from other initiatives. ).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      label: "Location of Sale".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/).freeze,
      subClassOf: "http://purl.org/goodrelations/v1/Location".freeze,
      type: "rdf:Class".freeze
    term :Network,
      :"dc:description" => %(A network of individuals and/or organizations that participate in the SSE. ).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      label: "Network".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/).freeze,
      subClassOf: "http://www.w3.org/ns/org/OrganizationColaboration".freeze,
      type: "rdf:Class".freeze
    term :OtherCosts,
      :"dc:description" => %(Other costs which impact on the final cost of a product or service provided by an SSE initiative, other than input or labour, like taxes, deprecation of machinery, funds, etc. The delivery costs are not included in these costs: they are included in the sale-options class.).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      label: "Other Costs".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/).freeze,
      type: "rdf:Class".freeze
    term :ProductOrService,
      :"dc:description" => %(The good offered by an SSE initiative. It may be material goods or provision of services. ).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      label: "Product or Service".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/).freeze,
      subClassOf: "http://purl.org/goodrelations/v1/ProductOrService".freeze,
      type: "rdf:Class".freeze
    term :SSEInitiative,
      :"dc:description" => %(An organization, practice, network, or other initiative that is recognized as belonging within the social solidarity economy.  ).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      label: "SSE Initiative".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/).freeze,
      subClassOf: "http://www.w3.org/ns/org/OrganizationUnit".freeze,
      type: "rdf:Class".freeze
    term :SaleOption,
      :"dc:description" => %(A Product sold at a certain price, under specific properties, in a certain Location. ).freeze,
      :"dc:issued" => %(2014-02-06).freeze,
      :"dc:modified" => %(2015-05-04).freeze,
      label: "Sale Option".freeze,
      :"rdfs:isDefinedBy" => %(http://purl.org/essglobal/vocab/).freeze,
      type: "rdf:Class".freeze
  end
end
